#127 [마이페이지] 회원 탈퇴 구현
familymoments/family-moments-android pull request #130
Opened 2024-06-21 18:57 UTC by whk06061

## 관련 이슈
- #127 
## 작업 내용
- [x] 회원 탈퇴 화면 구현
- [x] 회원 탈퇴 api 및 ViewModel 구현
## 리뷰 포인트
- 현재 서버 쪽에서 가족 권한이 있는 사용자는 탈퇴를 막고 있기 때문에 토미 PR 머지되면 리뷰해주세요!
## 스크린샷(선택)

2024-06-23 14:33 UTC, boring-km commented
가족 추가가 안되어서 테스트가 어렵습니다..!

2024-06-26 16:33 UTC, yewon-yw requested changes
가족 권한 확인 api 머지되었으니 반영해 주시면 다시 테스트해 볼게요!

2024-06-26 16:33 UTC, yewon-yw commented on app/src/main/java/io/familymoments/app/feature/deleteaccount/component/DeleteAccountPopup.kt
completePopUp을 사용해도 되지 않을까요?!

2024-06-26 16:33 UTC, yewon-yw commented on app/src/main/java/io/familymoments/app/feature/deleteaccount/viewmodel/DeleteAccountViewModel.kt
> +            onSuccess = { response ->
계정 탈퇴가 이루어지면 소셜 연결을 해제하는 코드가 추가되어야 할 것 같습니다!
아래 사이트 참고하시면 좋을 것 같아용
- [카카오 문서](https://developers.kakao.com/docs/latest/ko/kakaologin/common#unlink-and-deregister)
- [네이버 문서](https://developers.naver.com/docs/login/devguide/devguide.md#5-3-%EB%84%A4%EC%9D%B4%EB%B2%84-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%97%B0%EB%8F%99-%ED%95%B4%EC%A0%9C)

2024-06-28 09:31 UTC, whk06061 commented on app/src/main/java/io/familymoments/app/feature/deleteaccount/viewmodel/DeleteAccountViewModel.kt
> +            onSuccess = { response ->
감사합니당 😘 참고해서 열심히 구현했습니당 ㅎㅎ

2024-06-29 06:46 UTC, yewon-yw approved these changes
소셜 계정 탈퇴도 잘 되네욥👍

2024-06-29 12:49 UTC, merged