#86 [글 상세화면] 글 상세화면 코드 리팩토링
familymoments/family-moments-android pull request #90
Opened 2024-04-22 19:14 UTC by whk06061

## 관련 이슈
- #86 

## 작업 내용
- CommentUiState와 PostUiState 를 하나의 PostDetailUiState 로 합친다.
- UiState 가 popup 의 타입을 갖도록 하고, view 에서 이를 감지하여 적절한 popup 을 띄우도록 구현한다.

## 리뷰 포인트
- `PostDetailUiState` 에서 글 정보나 댓글 목록 불러오기 등 다른 api 의 경우 공통의 isSuccess 로 뷰 처리가 가능한데, 글이나 댓글에 하트 누르기/취소하기 요청을 보낼 때에는 이 응답에 대해서 성공일 때만 하트 아이콘을 바꿔야 합니당 그래서 공통의 isSuccess 외에 아래처럼 각 api 에 맞는 success 속성을 추가로 갖도록 했습니다. 
약간 일관성이 부족하다는 생각이 들어서 더 좋은 방법이 있다면 리뷰 마구마구 남겨주세요 🌝
![image](https://github.com/familymoments/family-moments-android/assets/63198157/3449f09e-f262-4c8e-8460-b2777aa90376)

## 스크린샷(선택)

2024-04-28 08:14 UTC, yewon-yw requested changes
리뷰가 늦어져서 죄송합니다😅 남겨놓은 코멘트 확인 부탁드려요!

2024-04-28 08:14 UTC, yewon-yw commented on app/src/main/java/io/familymoments/app/core/component/popup/LoveListPopUp.kt
>                      }
피그마를 보니까 이 부분은 없어도 될 것 같네요!

2024-04-28 08:14 UTC, yewon-yw commented on app/src/main/java/io/familymoments/app/feature/postdetail/screen/PostDetailScreen.kt
> +    }
제가 확인을 해봤는데 서버로부터 데이터를 받아오는 것 보다 화면이 먼저 그려지더라고요
그래서 `lovedState`와 `countLoveState`가 서버로부터 전달받은 `postInfo` 값으로 초기화되는 것이 아니라, `GetPostDetailResult`의 디폴트 값인 false와 0으로 초기화되고 있는 것 같습니다!
`postInfo` 값이 변경되어도 업데이트를 해주고 있지 않기 때문에 false와 0으로 초기화된 값을 계속 사용하게 되어 게시글 상세 화면의 좋아요와 좋아요 수가 이상하게 출력된 것 같습니다
```
LaunchedEffect(postInfo.loved) {
    lovedState = postInfo.loved
}
```
이런 식으로 좋아요와 좋아요 수를 업데이트 해줘야 할 것 같습니다

2024-04-28 08:14 UTC, yewon-yw commented on app/src/main/java/io/familymoments/app/feature/postdetail/screen/PostDetailScreen.kt
댓글 좋아요는 api에 문제가 있네요 수정요청 드려야 할 것 같습니다!

2024-04-28 08:14 UTC, yewon-yw commented on app/src/main/java/io/familymoments/app/feature/postdetail/viewmodel/PostDetailViewModel.kt
> +                getComments(_uiState.value.postDetail.postId)
댓글 삭제 후 화면에 반영이 되지 않는데 이건 왜 그럴까요😓🤔

2024-04-28 13:33 UTC, boring-km approved these changes
확인!

2024-04-28 13:33 UTC, boring-km commented on app/src/main/java/io/familymoments/app/feature/postdetail/uistate/PostDetailUiState.kt
> +    val deleteCommentLovesSuccess:Boolean? = null,
Nullable 말고 기본값을 false로 해서 타입을 Boolean으로 하는 건 어떨까요..?

2024-04-28 20:02 UTC, whk06061 commented on app/src/main/java/io/familymoments/app/feature/postdetail/viewmodel/PostDetailViewModel.kt
> +                getComments(_uiState.value.postDetail.postId)
제 폰에서는 잘 되는 것 같은데,,, 혹시 안드로이드 버전 몇으로 테스트하셨나용? 😭

2024-04-28 20:08 UTC, whk06061 commented on app/src/main/java/io/familymoments/app/feature/postdetail/screen/PostDetailScreen.kt
> +    }
😱😱😱😱😱😱미쳤네요,,,,,,아니 이런 실수를 하다니,,,, 감사합니닼ㅋㅋ 큐ㅠㅠㅠㅠ

2024-04-28 20:08 UTC, whk06061 commented on app/src/main/java/io/familymoments/app/core/component/popup/LoveListPopUp.kt
>                      }
반영했습니다!

2024-04-28 20:09 UTC, whk06061 commented on app/src/main/java/io/familymoments/app/feature/postdetail/uistate/PostDetailUiState.kt
> +    val deleteCommentLovesSuccess:Boolean? = null,
반영했습니다!ㅎㅎ

2024-04-29 03:06 UTC, merged

2024-04-29 03:11 UTC, yewon-yw commented on app/src/main/java/io/familymoments/app/feature/postdetail/viewmodel/PostDetailViewModel.kt
> +                getComments(_uiState.value.postDetail.postId)
실기기는 12버전으로, 에뮬레이터는 14버전으로 테스트했습니다!